# Generated by Django 2.1.5 on 2019-03-20 12:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='real_asset',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=13),
        ),
        migrations.AddField(
            model_name='profile',
            name='virtual_asset',
            field=models.PositiveIntegerField(default=17),
        ),
    ]
